/**
 * Auto-generated by: https://github.com/pmndrs/gltfjsx
 * Command: npx gltfjsx@6.5.3 public/models/SwampIslandv1.glb -o src/app/components/Swamp.tsx -k -K -r public -t
 *
 * @format
 */

import * as THREE from 'three';
import React from 'react';
import { Text, useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import OverLay from './OverLay';
import { useSwampStore } from '../core/store';
import { degToRad } from 'three/src/math/MathUtils.js';
import BtnOverLay from './BtnOverLay';

type GLTFResult = GLTF & {
	nodes: {
		Smoke: THREE.Mesh;
		group1003487641: THREE.Mesh;
		group1004619122_1: THREE.Mesh;
		group1004619122_2: THREE.Mesh;
		group1031434764: THREE.Mesh;
		group1050242619: THREE.Mesh;
		group1052670248_1: THREE.Mesh;
		group1052670248_2: THREE.Mesh;
		group1082366060: THREE.Mesh;
		group110025996: THREE.Mesh;
		group1142884108: THREE.Mesh;
		group1172879567: THREE.Mesh;
		group1174504232_1: THREE.Mesh;
		group1174504232_2: THREE.Mesh;
		group1214868813_1: THREE.Mesh;
		group1214868813_2: THREE.Mesh;
		group1238356241: THREE.Mesh;
		group1242887192: THREE.Mesh;
		group1258849289: THREE.Mesh;
		group1258849289_1: THREE.Mesh;
		group1277536336: THREE.Mesh;
		group1286523878_1: THREE.Mesh;
		group1286523878_2: THREE.Mesh;
		group129749433: THREE.Mesh;
		group1297782163: THREE.Mesh;
		group1309998384: THREE.Mesh;
		group1322395327_1: THREE.Mesh;
		group1322395327_2: THREE.Mesh;
		group1322395327_3: THREE.Mesh;
		group1327080236_1: THREE.Mesh;
		group1327080236_2: THREE.Mesh;
		group1336970504: THREE.Mesh;
		group1343099969: THREE.Mesh;
		group1358386406: THREE.Mesh;
		group1361306454: THREE.Mesh;
		group1365504722: THREE.Mesh;
		group1403107094_1: THREE.Mesh;
		group1403107094_2: THREE.Mesh;
		group1404788955_1: THREE.Mesh;
		group1404788955_2: THREE.Mesh;
		group1420377134_1: THREE.Mesh;
		group1420377134_2: THREE.Mesh;
		group145160911: THREE.Mesh;
		group1452085031: THREE.Mesh;
		group1458085261_1: THREE.Mesh;
		group1458085261_2: THREE.Mesh;
		group1461179098: THREE.Mesh;
		group1461848927_1: THREE.Mesh;
		group1461848927_2: THREE.Mesh;
		group1472950353_1: THREE.Mesh;
		group1472950353_2: THREE.Mesh;
		group1491434214: THREE.Mesh;
		group151683662_1: THREE.Mesh;
		group151683662_2: THREE.Mesh;
		group1542056423: THREE.Mesh;
		group1545068493_1: THREE.Mesh;
		group1545068493_2: THREE.Mesh;
		group1545068493_3: THREE.Mesh;
		group1551105044_1: THREE.Mesh;
		group1551105044_2: THREE.Mesh;
		group1567217949_1: THREE.Mesh;
		group1567217949_2: THREE.Mesh;
		group1567217949_3: THREE.Mesh;
		group1576524445_1: THREE.Mesh;
		group1576524445_2: THREE.Mesh;
		group1579994397: THREE.Mesh;
		group158387430: THREE.Mesh;
		group160733601: THREE.Mesh;
		group1612256777_1: THREE.Mesh;
		group1612256777_2: THREE.Mesh;
		group1612256777_3: THREE.Mesh;
		group1613210848_1: THREE.Mesh;
		group1613210848_2: THREE.Mesh;
		group1613210848_3: THREE.Mesh;
		group1613855375_1: THREE.Mesh;
		group1613855375_2: THREE.Mesh;
		group1619217945: THREE.Mesh;
		group1636920945: THREE.Mesh;
		group1659864640_1: THREE.Mesh;
		group1659864640_2: THREE.Mesh;
		group1659864640_3: THREE.Mesh;
		group1701987842_1: THREE.Mesh;
		group1701987842_2: THREE.Mesh;
		group171120536: THREE.Mesh;
		group1728000963: THREE.Mesh;
		group1730975042_1: THREE.Mesh;
		group1730975042_2: THREE.Mesh;
		group1730975042_3: THREE.Mesh;
		group1739923540: THREE.Mesh;
		group1747362787: THREE.Mesh;
		group176447540: THREE.Mesh;
		group176447540_1: THREE.Mesh;
		group1768964151: THREE.Mesh;
		group1774111551_1: THREE.Mesh;
		group1774111551_2: THREE.Mesh;
		group177470422: THREE.Mesh;
		group1776715167_1: THREE.Mesh;
		group1776715167_2: THREE.Mesh;
		group1779841807_1: THREE.Mesh;
		group1779841807_2: THREE.Mesh;
		group1779841807_3: THREE.Mesh;
		group1801059036: THREE.Mesh;
		group1824730829_1: THREE.Mesh;
		group1824730829_2: THREE.Mesh;
		group1832030168: THREE.Mesh;
		group1845677397: THREE.Mesh;
		group1861072529: THREE.Mesh;
		group1868357813: THREE.Mesh;
		group1894250264_1: THREE.Mesh;
		group1894250264_2: THREE.Mesh;
		group1894250264_3: THREE.Mesh;
		group1897236688_1: THREE.Mesh;
		group1897236688_2: THREE.Mesh;
		group1897236688_3: THREE.Mesh;
		group1901209621: THREE.Mesh;
		group1901253999_1: THREE.Mesh;
		group1901253999_2: THREE.Mesh;
		group1913496_1: THREE.Mesh;
		group1913496_2: THREE.Mesh;
		group1927904574: THREE.Mesh;
		group1929495238_1: THREE.Mesh;
		group1929495238_2: THREE.Mesh;
		group1936895037: THREE.Mesh;
		group1945336090_1: THREE.Mesh;
		group1945336090_2: THREE.Mesh;
		group1953012834_1: THREE.Mesh;
		group1953012834_2: THREE.Mesh;
		group1962738788_1: THREE.Mesh;
		group1962738788_2: THREE.Mesh;
		group1962738788_3: THREE.Mesh;
		group1967346599_1: THREE.Mesh;
		group1967346599_2: THREE.Mesh;
		group1967346599_3: THREE.Mesh;
		group198384851_1: THREE.Mesh;
		group198384851_2: THREE.Mesh;
		group1996960513: THREE.Mesh;
		group2006738021_1: THREE.Mesh;
		group2006738021_2: THREE.Mesh;
		group2008651517: THREE.Mesh;
		group2010240440_1: THREE.Mesh;
		group2010240440_2: THREE.Mesh;
		group2025685484: THREE.Mesh;
		group2029470574_1: THREE.Mesh;
		group2029470574_2: THREE.Mesh;
		group2032016018_1: THREE.Mesh;
		group2032016018_2: THREE.Mesh;
		group2032016018_3: THREE.Mesh;
		group2039324517: THREE.Mesh;
		group2041258262: THREE.Mesh;
		group2054480839: THREE.Mesh;
		group2068611164_1: THREE.Mesh;
		group2068611164_2: THREE.Mesh;
		group2068611164_3: THREE.Mesh;
		group2091126180: THREE.Mesh;
		group2094711981_1: THREE.Mesh;
		group2094711981_2: THREE.Mesh;
		group2097680475_1: THREE.Mesh;
		group2097680475_2: THREE.Mesh;
		group2099061238_1: THREE.Mesh;
		group2099061238_2: THREE.Mesh;
		group2111755826_1: THREE.Mesh;
		group2111755826_2: THREE.Mesh;
		group2111755826_3: THREE.Mesh;
		group2124268194: THREE.Mesh;
		group2127888576: THREE.Mesh;
		group2130633827_1: THREE.Mesh;
		group2130633827_2: THREE.Mesh;
		group2136008734: THREE.Mesh;
		group2141909856_1: THREE.Mesh;
		group2141909856_2: THREE.Mesh;
		group2141909856_3: THREE.Mesh;
		group2142730587: THREE.Mesh;
		group221385188: THREE.Mesh;
		group254298783: THREE.Mesh;
		group26026151: THREE.Mesh;
		group288751779_1: THREE.Mesh;
		group288751779_2: THREE.Mesh;
		group288751779_3: THREE.Mesh;
		group315252924: THREE.Mesh;
		group363956730_1: THREE.Mesh;
		group363956730_2: THREE.Mesh;
		group384158962: THREE.Mesh;
		group387975593_1: THREE.Mesh;
		group387975593_2: THREE.Mesh;
		group407773421: THREE.Mesh;
		group417366982_1: THREE.Mesh;
		group417366982_2: THREE.Mesh;
		group421353320: THREE.Mesh;
		group433455963_1: THREE.Mesh;
		group433455963_2: THREE.Mesh;
		group447178081_1: THREE.Mesh;
		group447178081_2: THREE.Mesh;
		group447178081_3: THREE.Mesh;
		group452827338: THREE.Mesh;
		group460493169: THREE.Mesh;
		group47637801_1: THREE.Mesh;
		group47637801_2: THREE.Mesh;
		group47637801_3: THREE.Mesh;
		group487098986_1: THREE.Mesh;
		group487098986_2: THREE.Mesh;
		group48834337_1: THREE.Mesh;
		group48834337_2: THREE.Mesh;
		group490728633: THREE.Mesh;
		group508170044_1: THREE.Mesh;
		group508170044_2: THREE.Mesh;
		group519474959_1: THREE.Mesh;
		group519474959_2: THREE.Mesh;
		group519474959_3: THREE.Mesh;
		group522174342: THREE.Mesh;
		group530821200: THREE.Mesh;
		group565166185: THREE.Mesh;
		group569347084_1: THREE.Mesh;
		group569347084_2: THREE.Mesh;
		group569347084_3: THREE.Mesh;
		group570053828: THREE.Mesh;
		group575425656: THREE.Mesh;
		group576487753: THREE.Mesh;
		group588255218: THREE.Mesh;
		group590414051: THREE.Mesh;
		group603141852: THREE.Mesh;
		group611773619: THREE.Mesh;
		group637660504_1: THREE.Mesh;
		group637660504_2: THREE.Mesh;
		group637660504_3: THREE.Mesh;
		group658148697_1: THREE.Mesh;
		group658148697_2: THREE.Mesh;
		group658148697_3: THREE.Mesh;
		group660072925_1: THREE.Mesh;
		group660072925_2: THREE.Mesh;
		group671896262: THREE.Mesh;
		group684750817_1: THREE.Mesh;
		group684750817_2: THREE.Mesh;
		group691286390_1: THREE.Mesh;
		group691286390_2: THREE.Mesh;
		group740347895_1: THREE.Mesh;
		group740347895_2: THREE.Mesh;
		group760265186_1: THREE.Mesh;
		group760265186_2: THREE.Mesh;
		group761897651_1: THREE.Mesh;
		group761897651_2: THREE.Mesh;
		group778790518_1: THREE.Mesh;
		group778790518_2: THREE.Mesh;
		group78677389_1: THREE.Mesh;
		group78677389_2: THREE.Mesh;
		group78677389_3: THREE.Mesh;
		group79247777: THREE.Mesh;
		group794915897_1: THREE.Mesh;
		group794915897_2: THREE.Mesh;
		group806275469: THREE.Mesh;
		group815898156: THREE.Mesh;
		group829808155: THREE.Mesh;
		group840329547: THREE.Mesh;
		group845297758: THREE.Mesh;
		group847447240_1: THREE.Mesh;
		group847447240_2: THREE.Mesh;
		group853010250: THREE.Mesh;
		group880033640: THREE.Mesh;
		group880052796: THREE.Mesh;
		group882103373: THREE.Mesh;
		group904865602: THREE.Mesh;
		group912524470_1: THREE.Mesh;
		group912524470_2: THREE.Mesh;
		group913185213_1: THREE.Mesh;
		group913185213_2: THREE.Mesh;
		group914355225: THREE.Mesh;
		group915963001: THREE.Mesh;
		group919541687_1: THREE.Mesh;
		group919541687_2: THREE.Mesh;
		group919541687_3: THREE.Mesh;
		group93090153: THREE.Mesh;
		group93944674_1: THREE.Mesh;
		group93944674_2: THREE.Mesh;
		group960311259_1: THREE.Mesh;
		group960311259_2: THREE.Mesh;
		group983657705: THREE.Mesh;
		Icosphere: THREE.Mesh;
		group1258849289001: THREE.Mesh;
		group1258849289001_1: THREE.Mesh;
	};
	materials: {
		Smoke: THREE.MeshStandardMaterial;
		mat19: THREE.MeshStandardMaterial;
		mat11: THREE.MeshStandardMaterial;
		mat20: THREE.MeshStandardMaterial;
		mat13: THREE.MeshStandardMaterial;
		mat10: THREE.MeshStandardMaterial;
		mat3: THREE.MeshStandardMaterial;
		mat9: THREE.MeshStandardMaterial;
		mat8: THREE.MeshStandardMaterial;
		mat12: THREE.MeshStandardMaterial;
		mat22: THREE.MeshStandardMaterial;
		mat14: THREE.MeshStandardMaterial;
		mat16: THREE.MeshStandardMaterial;
		mat23: THREE.MeshStandardMaterial;
	};
	animations: GLTFAction[];
};

export function Swamp(
	props: JSX.IntrinsicElements['group'] & { backBtnHandler: () => void }
) {
	const { nodes, materials } = useGLTF(
		'/models/SwampIslandv1.glb'
	) as GLTFResult;
	const { page } = useSwampStore();

	const { backBtnHandler } = props;

	return (
		<group
			{...props}
			dispose={null}>
			<group name='Scene'>
				<group
					name='RootNode'
					position={[0, 0, 0.721]}
					scale={0.028}>
					<mesh
						name='Smoke'
						geometry={nodes.Smoke.geometry}
						material={materials.Smoke}
						position={[-1.452, -0.133, 2.063]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
				</group>
				<group
					name='campfire'
					position={[-0.049, -0.058, 0.788]}
					scale={0.027}
				/>
				<mesh
					name='group1003487641'
					geometry={nodes.group1003487641.geometry}
					material={materials.mat19}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group1004619122'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1004619122_1'
						geometry={nodes.group1004619122_1.geometry}
						material={materials.mat11}
					/>
					<mesh
						name='group1004619122_2'
						geometry={nodes.group1004619122_2.geometry}
						material={materials.mat20}
					/>
				</group>
				<mesh
					name='group1031434764'
					geometry={nodes.group1031434764.geometry}
					material={materials.mat13}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group1050242619'
					geometry={nodes.group1050242619.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group1052670248'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1052670248_1'
						geometry={nodes.group1052670248_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name='group1052670248_2'
						geometry={nodes.group1052670248_2.geometry}
						material={materials.mat11}
					/>
				</group>
				<mesh
					name='group1082366060'
					geometry={nodes.group1082366060.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group110025996'
					geometry={nodes.group110025996.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group1142884108'
					geometry={nodes.group1142884108.geometry}
					material={materials.mat20}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group1172879567'
					geometry={nodes.group1172879567.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group1174504232'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1174504232_1'
						geometry={nodes.group1174504232_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name='group1174504232_2'
						geometry={nodes.group1174504232_2.geometry}
						material={materials.mat11}
					/>
				</group>
				<group
					name='group1214868813'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1214868813_1'
						geometry={nodes.group1214868813_1.geometry}
						material={materials.mat3}
					/>
					<mesh
						name='group1214868813_2'
						geometry={nodes.group1214868813_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<mesh
					name='group1238356241'
					geometry={nodes.group1238356241.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group1242887192'
					geometry={nodes.group1242887192.geometry}
					material={materials.mat20}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='Apple2'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1258849289'
						geometry={nodes.group1258849289.geometry}
						material={materials.mat10}
					/>
					<mesh
						name='group1258849289_1'
						geometry={nodes.group1258849289_1.geometry}
						material={materials.mat8}
					/>
				</group>
				<mesh
					name='group1277536336'
					geometry={nodes.group1277536336.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group1286523878'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1286523878_1'
						geometry={nodes.group1286523878_1.geometry}
						material={materials.mat3}
					/>
					<mesh
						name='group1286523878_2'
						geometry={nodes.group1286523878_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<mesh
					name='group129749433'
					geometry={nodes.group129749433.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group1297782163'
					geometry={nodes.group1297782163.geometry}
					material={materials.mat20}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group1309998384'
					geometry={nodes.group1309998384.geometry}
					material={materials.mat19}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group1322395327'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1322395327_1'
						geometry={nodes.group1322395327_1.geometry}
						material={materials.mat19}
					/>
					<mesh
						name='group1322395327_2'
						geometry={nodes.group1322395327_2.geometry}
						material={materials.mat12}
					/>
					<mesh
						name='group1322395327_3'
						geometry={nodes.group1322395327_3.geometry}
						material={materials.mat9}
					/>
				</group>
				<group
					name='group1327080236'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1327080236_1'
						geometry={nodes.group1327080236_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name='group1327080236_2'
						geometry={nodes.group1327080236_2.geometry}
						material={materials.mat11}
					/>
				</group>
				<mesh
					name='group1336970504'
					geometry={nodes.group1336970504.geometry}
					material={materials.mat22}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group1343099969'
					geometry={nodes.group1343099969.geometry}
					material={materials.mat22}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group1358386406'
					geometry={nodes.group1358386406.geometry}
					material={materials.mat19}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group1361306454'
					geometry={nodes.group1361306454.geometry}
					material={materials.mat20}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group1365504722'
					geometry={nodes.group1365504722.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group1403107094'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1403107094_1'
						geometry={nodes.group1403107094_1.geometry}
						material={materials.mat3}
					/>
					<mesh
						name='group1403107094_2'
						geometry={nodes.group1403107094_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<group
					name='group1404788955'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1404788955_1'
						geometry={nodes.group1404788955_1.geometry}
						material={materials.mat3}
					/>
					<mesh
						name='group1404788955_2'
						geometry={nodes.group1404788955_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<group
					name='group1420377134'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1420377134_1'
						geometry={nodes.group1420377134_1.geometry}
						material={materials.mat11}
					/>
					<mesh
						name='group1420377134_2'
						geometry={nodes.group1420377134_2.geometry}
						material={materials.mat20}
					/>
				</group>
				<mesh
					name='group145160911'
					geometry={nodes.group145160911.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group1452085031'
					geometry={nodes.group1452085031.geometry}
					material={materials.mat20}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group1458085261'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1458085261_1'
						geometry={nodes.group1458085261_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name='group1458085261_2'
						geometry={nodes.group1458085261_2.geometry}
						material={materials.mat11}
					/>
				</group>
				<mesh
					name='group1461179098'
					geometry={nodes.group1461179098.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group1461848927'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1461848927_1'
						geometry={nodes.group1461848927_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name='group1461848927_2'
						geometry={nodes.group1461848927_2.geometry}
						material={materials.mat11}
					/>
				</group>
				<group
					name='group1472950353'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1472950353_1'
						geometry={nodes.group1472950353_1.geometry}
						material={materials.mat11}
					/>
					<mesh
						name='group1472950353_2'
						geometry={nodes.group1472950353_2.geometry}
						material={materials.mat20}
					/>
				</group>
				<mesh
					name='group1491434214'
					geometry={nodes.group1491434214.geometry}
					material={materials.mat20}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group151683662'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group151683662_1'
						geometry={nodes.group151683662_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name='group151683662_2'
						geometry={nodes.group151683662_2.geometry}
						material={materials.mat13}
					/>
				</group>
				<mesh
					name='group1542056423'
					geometry={nodes.group1542056423.geometry}
					material={materials.mat20}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group1545068493'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1545068493_1'
						geometry={nodes.group1545068493_1.geometry}
						material={materials.mat12}
					/>
					<mesh
						name='group1545068493_2'
						geometry={nodes.group1545068493_2.geometry}
						material={materials.mat9}
					/>
					<mesh
						name='group1545068493_3'
						geometry={nodes.group1545068493_3.geometry}
						material={materials.mat19}
					/>
				</group>
				<group
					name='group1551105044'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1551105044_1'
						geometry={nodes.group1551105044_1.geometry}
						material={materials.mat3}
					/>
					<mesh
						name='group1551105044_2'
						geometry={nodes.group1551105044_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<group
					name='group1567217949'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1567217949_1'
						geometry={nodes.group1567217949_1.geometry}
						material={materials.mat19}
					/>
					<mesh
						name='group1567217949_2'
						geometry={nodes.group1567217949_2.geometry}
						material={materials.mat12}
					/>
					<mesh
						name='group1567217949_3'
						geometry={nodes.group1567217949_3.geometry}
						material={materials.mat9}
					/>
				</group>
				<group
					name='group1576524445'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1576524445_1'
						geometry={nodes.group1576524445_1.geometry}
						material={materials.mat3}
					/>
					<mesh
						name='group1576524445_2'
						geometry={nodes.group1576524445_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<mesh
					name='group1579994397'
					geometry={nodes.group1579994397.geometry}
					material={materials.mat14}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group158387430'
					geometry={nodes.group158387430.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group160733601'
					geometry={nodes.group160733601.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group1612256777'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1612256777_1'
						geometry={nodes.group1612256777_1.geometry}
						material={materials.mat12}
					/>
					<mesh
						name='group1612256777_2'
						geometry={nodes.group1612256777_2.geometry}
						material={materials.mat9}
					/>
					<mesh
						name='group1612256777_3'
						geometry={nodes.group1612256777_3.geometry}
						material={materials.mat19}
					/>
				</group>
				<group
					name='group1613210848'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1613210848_1'
						geometry={nodes.group1613210848_1.geometry}
						material={materials.mat12}
					/>
					<mesh
						name='group1613210848_2'
						geometry={nodes.group1613210848_2.geometry}
						material={materials.mat9}
					/>
					<mesh
						name='group1613210848_3'
						geometry={nodes.group1613210848_3.geometry}
						material={materials.mat19}
					/>
				</group>
				<group
					name='group1613855375'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1613855375_1'
						geometry={nodes.group1613855375_1.geometry}
						material={materials.mat12}
					/>
					<mesh
						name='group1613855375_2'
						geometry={nodes.group1613855375_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<mesh
					name='group1619217945'
					geometry={nodes.group1619217945.geometry}
					material={materials.mat19}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group1636920945'
					geometry={nodes.group1636920945.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group1659864640'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1659864640_1'
						geometry={nodes.group1659864640_1.geometry}
						material={materials.mat12}
					/>
					<mesh
						name='group1659864640_2'
						geometry={nodes.group1659864640_2.geometry}
						material={materials.mat9}
					/>
					<mesh
						name='group1659864640_3'
						geometry={nodes.group1659864640_3.geometry}
						material={materials.mat19}
					/>
				</group>
				<group
					name='group1701987842'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1701987842_1'
						geometry={nodes.group1701987842_1.geometry}
						material={materials.mat3}
					/>
					<mesh
						name='group1701987842_2'
						geometry={nodes.group1701987842_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<mesh
					name='group171120536'
					geometry={nodes.group171120536.geometry}
					material={materials.mat22}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group1728000963'
					geometry={nodes.group1728000963.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group1730975042'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1730975042_1'
						geometry={nodes.group1730975042_1.geometry}
						material={materials.mat12}
					/>
					<mesh
						name='group1730975042_2'
						geometry={nodes.group1730975042_2.geometry}
						material={materials.mat9}
					/>
					<mesh
						name='group1730975042_3'
						geometry={nodes.group1730975042_3.geometry}
						material={materials.mat19}
					/>
				</group>
				<mesh
					name='group1739923540'
					geometry={nodes.group1739923540.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group1747362787'
					geometry={nodes.group1747362787.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='tent'
					rotation={[Math.PI / 2, 0, 0]}>
					{page === 'home' && (
						<BtnOverLay
							rotation={[-Math.PI / 2, -1.1, 0]}
							position-x={1}
							position-y={-0.1}
							position-z={-0.8}
							onClick={backBtnHandler}
						/>
					)}
					<mesh
						name='group176447540'
						geometry={nodes.group176447540.geometry}
						material={materials.mat12}
					/>
					<mesh
						name='group176447540_1'
						geometry={nodes.group176447540_1.geometry}
						material={materials.mat14}
					/>
					{page === 'home' && (
						<OverLay
							rotation={[-Math.PI / 2, -1.1, 0]}
							position-x={1}
							position-y={-0.1}
							position-z={-0.4}
						/>
					)}
				</group>
				<mesh
					name='group1768964151'
					geometry={nodes.group1768964151.geometry}
					material={materials.mat16}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group1774111551'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1774111551_1'
						geometry={nodes.group1774111551_1.geometry}
						material={materials.mat8}
					/>
					<mesh
						name='group1774111551_2'
						geometry={nodes.group1774111551_2.geometry}
						material={materials.mat20}
					/>
				</group>
				<mesh
					name='group177470422'
					geometry={nodes.group177470422.geometry}
					material={materials.mat14}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group1776715167'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1776715167_1'
						geometry={nodes.group1776715167_1.geometry}
						material={materials.mat11}
					/>
					<mesh
						name='group1776715167_2'
						geometry={nodes.group1776715167_2.geometry}
						material={materials.mat20}
					/>
				</group>
				<group
					name='group1779841807'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1779841807_1'
						geometry={nodes.group1779841807_1.geometry}
						material={materials.mat12}
					/>
					<mesh
						name='group1779841807_2'
						geometry={nodes.group1779841807_2.geometry}
						material={materials.mat9}
					/>
					<mesh
						name='group1779841807_3'
						geometry={nodes.group1779841807_3.geometry}
						material={materials.mat19}
					/>
				</group>
				<mesh
					name='group1801059036'
					geometry={nodes.group1801059036.geometry}
					material={materials.mat16}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group1824730829'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1824730829_1'
						geometry={nodes.group1824730829_1.geometry}
						material={materials.mat19}
					/>
					<mesh
						name='group1824730829_2'
						geometry={nodes.group1824730829_2.geometry}
						material={materials.mat20}
					/>
				</group>
				<mesh
					name='group1832030168'
					geometry={nodes.group1832030168.geometry}
					material={materials.mat19}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group1845677397'
					geometry={nodes.group1845677397.geometry}
					material={materials.mat13}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group1861072529'
					geometry={nodes.group1861072529.geometry}
					material={materials.mat16}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group1868357813'
					geometry={nodes.group1868357813.geometry}
					material={materials.mat14}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group1894250264'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1894250264_1'
						geometry={nodes.group1894250264_1.geometry}
						material={materials.mat19}
					/>
					<mesh
						name='group1894250264_2'
						geometry={nodes.group1894250264_2.geometry}
						material={materials.mat12}
					/>
					<mesh
						name='group1894250264_3'
						geometry={nodes.group1894250264_3.geometry}
						material={materials.mat9}
					/>
				</group>
				<group
					name='group1897236688'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1897236688_1'
						geometry={nodes.group1897236688_1.geometry}
						material={materials.mat9}
					/>
					<mesh
						name='group1897236688_2'
						geometry={nodes.group1897236688_2.geometry}
						material={materials.mat12}
					/>
					<mesh
						name='group1897236688_3'
						geometry={nodes.group1897236688_3.geometry}
						material={materials.mat19}
					/>
				</group>
				<mesh
					name='group1901209621'
					geometry={nodes.group1901209621.geometry}
					material={materials.mat22}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group1901253999'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1901253999_1'
						geometry={nodes.group1901253999_1.geometry}
						material={materials.mat9}
					/>
					<mesh
						name='group1901253999_2'
						geometry={nodes.group1901253999_2.geometry}
						material={materials.mat3}
					/>
				</group>
				<group
					name='group1913496'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1913496_1'
						geometry={nodes.group1913496_1.geometry}
						material={materials.mat3}
					/>
					<mesh
						name='group1913496_2'
						geometry={nodes.group1913496_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<mesh
					name='group1927904574'
					geometry={nodes.group1927904574.geometry}
					material={materials.mat20}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group1929495238'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1929495238_1'
						geometry={nodes.group1929495238_1.geometry}
						material={materials.mat8}
					/>
					<mesh
						name='group1929495238_2'
						geometry={nodes.group1929495238_2.geometry}
						material={materials.mat10}
					/>
				</group>
				<mesh
					name='group1936895037'
					geometry={nodes.group1936895037.geometry}
					material={materials.mat20}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group1945336090'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1945336090_1'
						geometry={nodes.group1945336090_1.geometry}
						material={materials.mat8}
					/>
					<mesh
						name='group1945336090_2'
						geometry={nodes.group1945336090_2.geometry}
						material={materials.mat10}
					/>
				</group>
				<group
					name='group1953012834'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1953012834_1'
						geometry={nodes.group1953012834_1.geometry}
						material={materials.mat3}
					/>
					<mesh
						name='group1953012834_2'
						geometry={nodes.group1953012834_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<group
					name='group1962738788'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1962738788_1'
						geometry={nodes.group1962738788_1.geometry}
						material={materials.mat12}
					/>
					<mesh
						name='group1962738788_2'
						geometry={nodes.group1962738788_2.geometry}
						material={materials.mat9}
					/>
					<mesh
						name='group1962738788_3'
						geometry={nodes.group1962738788_3.geometry}
						material={materials.mat19}
					/>
				</group>
				<group
					name='group1967346599'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1967346599_1'
						geometry={nodes.group1967346599_1.geometry}
						material={materials.mat9}
					/>
					<mesh
						name='group1967346599_2'
						geometry={nodes.group1967346599_2.geometry}
						material={materials.mat22}
					/>
					<mesh
						name='group1967346599_3'
						geometry={nodes.group1967346599_3.geometry}
						material={materials.mat3}
					/>
				</group>
				<group
					name='group198384851'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group198384851_1'
						geometry={nodes.group198384851_1.geometry}
						material={materials.mat3}
					/>
					<mesh
						name='group198384851_2'
						geometry={nodes.group198384851_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<mesh
					name='group1996960513'
					geometry={nodes.group1996960513.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group2006738021'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group2006738021_1'
						geometry={nodes.group2006738021_1.geometry}
						material={materials.mat3}
					/>
					<mesh
						name='group2006738021_2'
						geometry={nodes.group2006738021_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<mesh
					name='group2008651517'
					geometry={nodes.group2008651517.geometry}
					material={materials.mat22}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group2010240440'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group2010240440_1'
						geometry={nodes.group2010240440_1.geometry}
						material={materials.mat3}
					/>
					<mesh
						name='group2010240440_2'
						geometry={nodes.group2010240440_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<mesh
					name='group2025685484'
					geometry={nodes.group2025685484.geometry}
					material={materials.mat16}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group2029470574'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group2029470574_1'
						geometry={nodes.group2029470574_1.geometry}
						material={materials.mat9}
					/>
					<mesh
						name='group2029470574_2'
						geometry={nodes.group2029470574_2.geometry}
						material={materials.mat12}
					/>
				</group>
				<group
					name='group2032016018'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group2032016018_1'
						geometry={nodes.group2032016018_1.geometry}
						material={materials.mat12}
					/>
					<mesh
						name='group2032016018_2'
						geometry={nodes.group2032016018_2.geometry}
						material={materials.mat9}
					/>
					<mesh
						name='group2032016018_3'
						geometry={nodes.group2032016018_3.geometry}
						material={materials.mat19}
					/>
				</group>
				<mesh
					name='group2039324517'
					geometry={nodes.group2039324517.geometry}
					material={materials.mat23}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group2041258262'
					geometry={nodes.group2041258262.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group2054480839'
					geometry={nodes.group2054480839.geometry}
					material={materials.mat22}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group2068611164'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group2068611164_1'
						geometry={nodes.group2068611164_1.geometry}
						material={materials.mat9}
					/>
					<mesh
						name='group2068611164_2'
						geometry={nodes.group2068611164_2.geometry}
						material={materials.mat19}
					/>
					<mesh
						name='group2068611164_3'
						geometry={nodes.group2068611164_3.geometry}
						material={materials.mat12}
					/>
				</group>
				<mesh
					name='group2091126180'
					geometry={nodes.group2091126180.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group2094711981'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group2094711981_1'
						geometry={nodes.group2094711981_1.geometry}
						material={materials.mat3}
					/>
					<mesh
						name='group2094711981_2'
						geometry={nodes.group2094711981_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<group
					name='group2097680475'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group2097680475_1'
						geometry={nodes.group2097680475_1.geometry}
						material={materials.mat3}
					/>
					<mesh
						name='group2097680475_2'
						geometry={nodes.group2097680475_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<group
					name='group2099061238'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group2099061238_1'
						geometry={nodes.group2099061238_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name='group2099061238_2'
						geometry={nodes.group2099061238_2.geometry}
						material={materials.mat11}
					/>
				</group>
				<group
					name='group2111755826'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group2111755826_1'
						geometry={nodes.group2111755826_1.geometry}
						material={materials.mat19}
					/>
					<mesh
						name='group2111755826_2'
						geometry={nodes.group2111755826_2.geometry}
						material={materials.mat12}
					/>
					<mesh
						name='group2111755826_3'
						geometry={nodes.group2111755826_3.geometry}
						material={materials.mat9}
					/>
				</group>
				<mesh
					name='group2124268194'
					geometry={nodes.group2124268194.geometry}
					material={materials.mat16}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group2127888576'
					geometry={nodes.group2127888576.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group2130633827'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group2130633827_1'
						geometry={nodes.group2130633827_1.geometry}
						material={materials.mat3}
					/>
					<mesh
						name='group2130633827_2'
						geometry={nodes.group2130633827_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<mesh
					name='group2136008734'
					geometry={nodes.group2136008734.geometry}
					material={materials.mat11}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group2141909856'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group2141909856_1'
						geometry={nodes.group2141909856_1.geometry}
						material={materials.mat9}
					/>
					<mesh
						name='group2141909856_2'
						geometry={nodes.group2141909856_2.geometry}
						material={materials.mat12}
					/>
					<mesh
						name='group2141909856_3'
						geometry={nodes.group2141909856_3.geometry}
						material={materials.mat19}
					/>
				</group>
				<mesh
					name='group2142730587'
					geometry={nodes.group2142730587.geometry}
					material={materials.mat22}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group221385188'
					geometry={nodes.group221385188.geometry}
					material={materials.mat19}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group254298783'
					geometry={nodes.group254298783.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group26026151'
					geometry={nodes.group26026151.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group288751779'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group288751779_1'
						geometry={nodes.group288751779_1.geometry}
						material={materials.mat12}
					/>
					<mesh
						name='group288751779_2'
						geometry={nodes.group288751779_2.geometry}
						material={materials.mat9}
					/>
					<mesh
						name='group288751779_3'
						geometry={nodes.group288751779_3.geometry}
						material={materials.mat19}
					/>
				</group>
				<mesh
					name='group315252924'
					geometry={nodes.group315252924.geometry}
					material={materials.mat22}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group363956730'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group363956730_1'
						geometry={nodes.group363956730_1.geometry}
						material={materials.mat9}
					/>
					<mesh
						name='group363956730_2'
						geometry={nodes.group363956730_2.geometry}
						material={materials.mat3}
					/>
				</group>
				<mesh
					name='group384158962'
					geometry={nodes.group384158962.geometry}
					material={materials.mat22}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group387975593'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group387975593_1'
						geometry={nodes.group387975593_1.geometry}
						material={materials.mat3}
					/>
					<mesh
						name='group387975593_2'
						geometry={nodes.group387975593_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<mesh
					name='group407773421'
					geometry={nodes.group407773421.geometry}
					material={materials.mat16}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group417366982'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group417366982_1'
						geometry={nodes.group417366982_1.geometry}
						material={materials.mat3}
					/>
					<mesh
						name='group417366982_2'
						geometry={nodes.group417366982_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<mesh
					name='group421353320'
					geometry={nodes.group421353320.geometry}
					material={materials.mat16}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group433455963'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group433455963_1'
						geometry={nodes.group433455963_1.geometry}
						material={materials.mat3}
					/>
					<mesh
						name='group433455963_2'
						geometry={nodes.group433455963_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<group
					name='group447178081'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group447178081_1'
						geometry={nodes.group447178081_1.geometry}
						material={materials.mat12}
					/>
					<mesh
						name='group447178081_2'
						geometry={nodes.group447178081_2.geometry}
						material={materials.mat9}
					/>
					<mesh
						name='group447178081_3'
						geometry={nodes.group447178081_3.geometry}
						material={materials.mat19}
					/>
				</group>
				<mesh
					name='group452827338'
					geometry={nodes.group452827338.geometry}
					material={materials.mat14}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group460493169'
					geometry={nodes.group460493169.geometry}
					material={materials.mat22}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group47637801'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group47637801_1'
						geometry={nodes.group47637801_1.geometry}
						material={materials.mat19}
					/>
					<mesh
						name='group47637801_2'
						geometry={nodes.group47637801_2.geometry}
						material={materials.mat12}
					/>
					<mesh
						name='group47637801_3'
						geometry={nodes.group47637801_3.geometry}
						material={materials.mat9}
					/>
				</group>
				<group
					name='group487098986'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group487098986_1'
						geometry={nodes.group487098986_1.geometry}
						material={materials.mat3}
					/>
					<mesh
						name='group487098986_2'
						geometry={nodes.group487098986_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<group
					name='group48834337'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group48834337_1'
						geometry={nodes.group48834337_1.geometry}
						material={materials.mat3}
					/>
					<mesh
						name='group48834337_2'
						geometry={nodes.group48834337_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<mesh
					name='group490728633'
					geometry={nodes.group490728633.geometry}
					material={materials.mat20}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group508170044'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group508170044_1'
						geometry={nodes.group508170044_1.geometry}
						material={materials.mat9}
					/>
					<mesh
						name='group508170044_2'
						geometry={nodes.group508170044_2.geometry}
						material={materials.mat3}
					/>
				</group>
				<group
					name='group519474959'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group519474959_1'
						geometry={nodes.group519474959_1.geometry}
						material={materials.mat19}
					/>
					<mesh
						name='group519474959_2'
						geometry={nodes.group519474959_2.geometry}
						material={materials.mat9}
					/>
					<mesh
						name='group519474959_3'
						geometry={nodes.group519474959_3.geometry}
						material={materials.mat12}
					/>
				</group>
				<mesh
					name='group522174342'
					geometry={nodes.group522174342.geometry}
					material={materials.mat14}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group530821200'
					geometry={nodes.group530821200.geometry}
					material={materials.mat22}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group565166185'
					geometry={nodes.group565166185.geometry}
					material={materials.mat22}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group569347084'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group569347084_1'
						geometry={nodes.group569347084_1.geometry}
						material={materials.mat19}
					/>
					<mesh
						name='group569347084_2'
						geometry={nodes.group569347084_2.geometry}
						material={materials.mat9}
					/>
					<mesh
						name='group569347084_3'
						geometry={nodes.group569347084_3.geometry}
						material={materials.mat12}
					/>
				</group>
				<mesh
					name='group570053828'
					geometry={nodes.group570053828.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group575425656'
					geometry={nodes.group575425656.geometry}
					material={materials.mat13}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group576487753'
					geometry={nodes.group576487753.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group588255218'
					geometry={nodes.group588255218.geometry}
					material={materials.mat19}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group590414051'
					geometry={nodes.group590414051.geometry}
					material={materials.mat22}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group603141852'
					geometry={nodes.group603141852.geometry}
					material={materials.mat20}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group611773619'
					geometry={nodes.group611773619.geometry}
					material={materials.mat16}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group637660504'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group637660504_1'
						geometry={nodes.group637660504_1.geometry}
						material={materials.mat9}
					/>
					<mesh
						name='group637660504_2'
						geometry={nodes.group637660504_2.geometry}
						material={materials.mat19}
					/>
					<mesh
						name='group637660504_3'
						geometry={nodes.group637660504_3.geometry}
						material={materials.mat12}
					/>
				</group>
				<group
					name='group658148697'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group658148697_1'
						geometry={nodes.group658148697_1.geometry}
						material={materials.mat9}
					/>
					<mesh
						name='group658148697_2'
						geometry={nodes.group658148697_2.geometry}
						material={materials.mat12}
					/>
					<mesh
						name='group658148697_3'
						geometry={nodes.group658148697_3.geometry}
						material={materials.mat19}
					/>
				</group>
				<group
					name='group660072925'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group660072925_1'
						geometry={nodes.group660072925_1.geometry}
						material={materials.mat3}
					/>
					<mesh
						name='group660072925_2'
						geometry={nodes.group660072925_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<mesh
					name='group671896262'
					geometry={nodes.group671896262.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group684750817'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group684750817_1'
						geometry={nodes.group684750817_1.geometry}
						material={materials.mat11}
					/>
					<mesh
						name='group684750817_2'
						geometry={nodes.group684750817_2.geometry}
						material={materials.mat20}
					/>
				</group>
				<group
					name='group691286390'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group691286390_1'
						geometry={nodes.group691286390_1.geometry}
						material={materials.mat3}
					/>
					<mesh
						name='group691286390_2'
						geometry={nodes.group691286390_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<group
					name='group740347895'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group740347895_1'
						geometry={nodes.group740347895_1.geometry}
						material={materials.mat3}
					/>
					<mesh
						name='group740347895_2'
						geometry={nodes.group740347895_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<group
					name='group760265186'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group760265186_1'
						geometry={nodes.group760265186_1.geometry}
						material={materials.mat11}
					/>
					<mesh
						name='group760265186_2'
						geometry={nodes.group760265186_2.geometry}
						material={materials.mat20}
					/>
				</group>
				<group
					name='group761897651'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group761897651_1'
						geometry={nodes.group761897651_1.geometry}
						material={materials.mat11}
					/>
					<mesh
						name='group761897651_2'
						geometry={nodes.group761897651_2.geometry}
						material={materials.mat20}
					/>
				</group>
				<group
					name='group778790518'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group778790518_1'
						geometry={nodes.group778790518_1.geometry}
						material={materials.mat9}
					/>
					<mesh
						name='group778790518_2'
						geometry={nodes.group778790518_2.geometry}
						material={materials.mat12}
					/>
				</group>
				<group
					name='group78677389'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group78677389_1'
						geometry={nodes.group78677389_1.geometry}
						material={materials.mat12}
					/>
					<mesh
						name='group78677389_2'
						geometry={nodes.group78677389_2.geometry}
						material={materials.mat19}
					/>
					<mesh
						name='group78677389_3'
						geometry={nodes.group78677389_3.geometry}
						material={materials.mat9}
					/>
				</group>
				<mesh
					name='group79247777'
					geometry={nodes.group79247777.geometry}
					material={materials.mat20}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group794915897'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group794915897_1'
						geometry={nodes.group794915897_1.geometry}
						material={materials.mat9}
					/>
					<mesh
						name='group794915897_2'
						geometry={nodes.group794915897_2.geometry}
						material={materials.mat12}
					/>
				</group>
				<mesh
					name='group806275469'
					geometry={nodes.group806275469.geometry}
					material={materials.mat14}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group815898156'
					geometry={nodes.group815898156.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group829808155'
					geometry={nodes.group829808155.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group840329547'
					geometry={nodes.group840329547.geometry}
					material={materials.mat16}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group845297758'
					geometry={nodes.group845297758.geometry}
					material={materials.mat13}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group847447240'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group847447240_1'
						geometry={nodes.group847447240_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name='group847447240_2'
						geometry={nodes.group847447240_2.geometry}
						material={materials.mat11}
					/>
				</group>
				<mesh
					name='group853010250'
					geometry={nodes.group853010250.geometry}
					material={materials.mat20}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group880033640'
					geometry={nodes.group880033640.geometry}
					material={materials.mat20}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group880052796'
					geometry={nodes.group880052796.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group882103373'
					geometry={nodes.group882103373.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group904865602'
					geometry={nodes.group904865602.geometry}
					material={materials.mat22}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group912524470'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group912524470_1'
						geometry={nodes.group912524470_1.geometry}
						material={materials.mat11}
					/>
					<mesh
						name='group912524470_2'
						geometry={nodes.group912524470_2.geometry}
						material={materials.mat20}
					/>
				</group>
				<group
					name='group913185213'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group913185213_1'
						geometry={nodes.group913185213_1.geometry}
						material={materials.mat3}
					/>
					<mesh
						name='group913185213_2'
						geometry={nodes.group913185213_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<mesh
					name='group914355225'
					geometry={nodes.group914355225.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='group915963001'
					geometry={nodes.group915963001.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group919541687'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group919541687_1'
						geometry={nodes.group919541687_1.geometry}
						material={materials.mat19}
					/>
					<mesh
						name='group919541687_2'
						geometry={nodes.group919541687_2.geometry}
						material={materials.mat12}
					/>
					<mesh
						name='group919541687_3'
						geometry={nodes.group919541687_3.geometry}
						material={materials.mat9}
					/>
				</group>
				<mesh
					name='group93090153'
					geometry={nodes.group93090153.geometry}
					material={materials.mat10}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name='group93944674'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group93944674_1'
						geometry={nodes.group93944674_1.geometry}
						material={materials.mat8}
					/>
					<mesh
						name='group93944674_2'
						geometry={nodes.group93944674_2.geometry}
						material={materials.mat10}
					/>
				</group>
				<group
					name='group960311259'
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group960311259_1'
						geometry={nodes.group960311259_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name='group960311259_2'
						geometry={nodes.group960311259_2.geometry}
						material={materials.mat11}
					/>
				</group>
				<mesh
					name='group983657705'
					geometry={nodes.group983657705.geometry}
					material={materials.mat14}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name='Icosphere'
					geometry={nodes.Icosphere.geometry}
					material={nodes.Icosphere.material}
					position={[0, -0.243, 0]}
					scale={0.02}
				/>
				<group
					name='Apple1'
					position={[0.062, -0.001, 0.004]}
					rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						name='group1258849289001'
						geometry={nodes.group1258849289001.geometry}
						material={materials.mat10}
					/>
					<mesh
						name='group1258849289001_1'
						geometry={nodes.group1258849289001_1.geometry}
						material={materials.mat8}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload('/models/SwampIslandv1.glb');
